#!/bin/bash
set -eu -o pipefail

OUTPUT_FILE=/opt/transaction-executor/bin/run-init-tx-executor

VAULT_DNS=$1
VAULT_PORT=$2

VAULT_URL="https://$VAULT_DNS:$VAULT_PORT"

# Write the run-init-tx-executor script
cat << EOF_OUTER > $OUTPUT_FILE
#!/bin/bash
set -eu -o pipefail

SUPERVISOR_CONFIG="/etc/supervisor/conf.d/init-tx-executor-supervisor.conf"

# Write the init-tx-executor supervisor config
cat << EOF > \$SUPERVISOR_CONFIG
[program:init-tx-executor]
command=/opt/transaction-executor/bin/init-tx-executor.sh
stdout_logfile=/opt/transaction-executor/log/init-tx-executor-stdout.log
stderr_logfile=/opt/transaction-executor/log/init-tx-executor-error.log
numprocs=1
autostart=true
autorestart=unexpected
stopsignal=INT
user=ubuntu
environment=VAULT_ADDR=$VAULT_URL
EOF

# Read and run the supervisor config
sudo supervisorctl reread
sudo supervisorctl update
EOF_OUTER

# Give permission to run the script
sudo chown ubuntu $OUTPUT_FILE
sudo chmod 744 $OUTPUT_FILE
